### PR TITLE
Non-linears model, refactored and other

### PR DESCRIPTION
**Pull request by dvolkow**

### CODE REVIEW

**Comment by sir-chaos** [comment]
I'm in process with review. Here are some thoughts:
1. The formatting you used is not PEP. This would be nice for the future, Python has very strict code style, but now it's really not the biggest issue. I suggest you study this topic later, and for now I won't comment formatting at all.
2. You _almost_ succseeded in speeding up the calculation via numpy. To make it work much, much faster, pay attenion to statements like `np.array([2 for i in range(len(data.b))])` in mle_types.py. You need to use numpy method `np.repeat(2, len(data.b))`. You can even save the data length, but it doesnt really make difference.
I replaced ~3 statements like that in `mle_types.py` and the program sped up.
3. The tuple-assignment I recommended dont seem to work very well with np.array, so MLE_START should either be stored as list, or by-item assignment used.

**Comment by sir-chaos** [comment]
Actually, never mind what I wrote in paragraph 3, its wrong (all works with np.array too)

**Comment by sir-chaos** [comment]
It seems, you've accidently turned V_sun negative twice: while assigning beta[]'s and in the v_sun function itself. Changing the sign in one place makes the iterations converge and result be more trustful (R_0 ~ 7.17 _without_ falling to ~2.0)

**Comment by dvolkow** [comment]
fix par. 2 and neg. v_sun

**Comment by sir-chaos** [comment]
One last place you have to fix to increase performance:
np.sqrt(np.repeat(r0 ** 2, len(data.b)) in `mle_types.py`

**Comment by sir-chaos** [comment]
https://pastebin.com/gTe8CvRa

Here is an implementation of jack-of-all-trades binary search formal error estimation. Althou it's not very fast, you can always use it in solving problems like this. I suggest ypu implement another method for error estimation later.

For your model with theta=2, I got the following values:

--------MLE_SOLUTION:--------
LF value  145599.92531975333
R_0:    7.17790030831
A:      12.1739466641
u:      11.582244023
v:      27.6879773651
w:      6.40508665882
theta0:  -1.58394462674

errors:
array([[-0.2768819 ,  0.97784872],
       [-0.49040557,  0.18724576],
       [-0.85113658,  0.63057627],
       [-0.64555709,  1.86907367],
       [-2.04850184,  1.41675013],
       [ 0.39598616, -0.39598616]])

**Pull request merged**
